### ISSUE TITLE
Problem on installation from pip

### ISSUE THREAD

**Issue by eamanu** [JeffCarpenter/flask-bootstrap4#1]
I have an exception when I install flask-bootstrap4 from pip:

pip install flask_bootstrap4
Collecting flask_bootstrap4
  Downloading https://files.pythonhosted.org/packages/79/39/10e7248d003af4a835931856c165d990034322da5d741f89ed51ea8479fa/Flask_Bootstrap4-4.0.2-py3-none-any.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 764kB/s 
Collecting visitor (from flask_bootstrap4)
  Downloading https://files.pythonhosted.org/packages/d7/58/785fcd6de4210049da5fafe62301b197f044f3835393594be368547142b0/visitor-0.1.3.tar.gz
Collecting dominate (from flask_bootstrap4)
  Downloading https://files.pythonhosted.org/packages/1a/54/50ec03a4b4114e2c02d049cc26fe6ad8f0653ba5d0cd55d7c9bf9a260434/dominate-2.3.5-py2.py3-none-any.whl
Requirement already satisfied: Flask>=0.8 in ./venv/lib/python3.5/site-packages (from flask_bootstrap4)
Requirement already satisfied: Jinja2>=2.10 in ./venv/lib/python3.5/site-packages (from Flask>=0.8->flask_bootstrap4)
Requirement already satisfied: Werkzeug>=0.14 in ./venv/lib/python3.5/site-packages (from Flask>=0.8->flask_bootstrap4)
Requirement already satisfied: click>=5.1 in ./venv/lib/python3.5/site-packages (from Flask>=0.8->flask_bootstrap4)
Requirement already satisfied: itsdangerous>=0.24 in ./venv/lib/python3.5/site-packages (from Flask>=0.8->flask_bootstrap4)
Requirement already satisfied: MarkupSafe>=0.23 in ./venv/lib/python3.5/site-packages (from Jinja2>=2.10->Flask>=0.8->flask_bootstrap4)
Building wheels for collected packages: visitor
  Running setup.py bdist_wheel for visitor ... error
  Complete output from command /home/eamanu/dev/Satellogic/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4v75449i/visitor/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp237nd9j3pip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for visitor
  Running setup.py clean for visitor
Failed to build visitor
Installing collected packages: visitor, dominate, flask-bootstrap4
  Running setup.py install for visitor ... done
Successfully installed dominate-2.3.5 flask-bootstrap4-4.0.2 visitor-0.1.3

**Comment by JeffCarpenter** [comment]
The error occurs when building the visitor package, so if it is still affects you report the issue there.
